//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralApi.Models.Parcial
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class parcial_sapEntities : DbContext
    {
        public parcial_sapEntities()
            : base("name=parcial_sapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Detalle_de_transaccion> Detalle_de_transaccion { get; set; }
        public virtual DbSet<inventario> inventario { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<sucursal> sucursal { get; set; }
        public virtual DbSet<tipo_sucursal> tipo_sucursal { get; set; }
        public virtual DbSet<transaccion> transaccion { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
