//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralApi.Models.Parcial
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaccion
    {
        public int id_transaccion { get; set; }
        public Nullable<int> id_origen { get; set; }
        public Nullable<int> id_destino { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<System.DateTime> Fecha_de_transaccion { get; set; }
    }
}
